export enum PostKind {
  'LIGHTNING_TALK' = 'LIGHTNING_TALK',
  'DEVELOPMENT_TIP' = 'DEVELOPMENT_TIP',
  'STUDY_SHARE' = 'STUDY_SHARE',
  'PROJECT_SHARE' = 'PROJECT_SHARE',
  'V_LOG' = 'V_LOG',
}

PostKind.LIGHTNING_TALK;
