name: ci
on:
  pull_request:
    branches:
      - main
      - development
      - 'feature/**'

  push:
    branches:
      - main
      - development
      - 'feature/**'
jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Dependencies
        run: yarn install
        working-directory: ./web-app

      - name: Next Build
        run: yarn build
        working-directory: ./web-app

      - name: Docker Build
        run: |
          docker build -t test .
        working-directory: ./web-app
        env:
          USER_NAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
